// ===== Runtime EuroBasket Cache Loader =====
// Lazy-fetches per-player JSON from /data/cache/ when a player profile opens.
// Adds verified winter-team / overseas-league info that doesn't fit in the
// static data files (which focus on CEBL summer teams).
//
// The cache is generated by tools/cache-updater.js (build-time) and published
// as static JSON. No backend; the browser fetches a single JSON per request.

const _cacheStore = new Map();

function _slugify(name) {
  return name
    .toLowerCase()
    .replace(/['']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

async function fetchPlayerCache(playerName) {
  if (!playerName) return null;
  const slug = _slugify(playerName);
  if (_cacheStore.has(slug)) return _cacheStore.get(slug);

  try {
    // Use default cache; browser HTTP cache decides freshness based on server headers.
    const res = await fetch(`data/cache/${slug}.json`);
    if (!res.ok) {
      _cacheStore.set(slug, null);
      return null;
    }
    const data = await res.json();
    // Cross-check: if cached fullName diverges sharply, ignore (avoids the
    // Chris-Jones-as-Cat-Barber bug from earlier scrapes).
    const requested = playerName.toLowerCase().split(/\s+/);
    const cached = (data.fullName || '').toLowerCase();
    const matchesAny = requested.some(part => part.length > 2 && cached.includes(part));
    if (!matchesAny) {
      _cacheStore.set(slug, null);
      return null;
    }
    _cacheStore.set(slug, data);
    return data;
  } catch (e) {
    _cacheStore.set(slug, null);
    return null;
  }
}

// --- Build a freshness label like "Verified 2 days ago" ---
function _freshnessLabel(iso) {
  if (!iso) return null;
  const t = new Date(iso).getTime();
  if (!t) return null;
  const ageDays = Math.floor((Date.now() - t) / (1000 * 60 * 60 * 24));
  if (ageDays === 0) return 'Verified today';
  if (ageDays === 1) return 'Verified yesterday';
  if (ageDays < 14) return `Verified ${ageDays} days ago`;
  if (ageDays < 60) return `Verified ${Math.floor(ageDays / 7)} weeks ago`;
  if (ageDays < 365) return `Verified ${Math.floor(ageDays / 30)} months ago`;
  return `Verified ${Math.floor(ageDays / 365)}y ago`;
}

// --- Render block to inject into player modal ---
function renderEuroBasketBlock(cache) {
  if (!cache) return '';
  const rows = [];
  if (cache.currentTeam || cache.currentLeague) {
    rows.push(['Winter Team', `${cache.currentTeam || '?'} ${cache.currentLeague ? '(' + cache.currentLeague + ')' : ''}`]);
  }
  if (cache.birthCity) rows.push(['Birth City', cache.birthCity]);
  if (cache.height && cache.heightCm) rows.push(['Height', `${cache.height} (${cache.heightCm} cm)`]);
  if (cache.weight && cache.weightKg) rows.push(['Weight', `${cache.weight} lbs (${cache.weightKg} kg)`]);
  if (cache.position) rows.push(['Position', cache.position]);
  if (cache.nationality) rows.push(['Nationality', cache.nationality]);
  if (cache.college && cache.college !== 'undefined') rows.push(['College', cache.college]);
  if (cache.highSchool) rows.push(['High School', cache.highSchool]);
  if (cache.agent) rows.push(['Agent', cache.agent]);

  const recentSeasons = (cache.careerHistory || []).slice(-6).reverse();
  const freshness = _freshnessLabel(cache._lastVerified || cache.cachedAt);
  const sourceCount = (cache._sources || ['eurobasket.com']).length;
  const confidence = cache._dataConfidence || (cache.fullName && cache.currentTeam ? 'high' : 'medium');

  return `
    <div class="eurobasket-block">
      <div class="eb-header">
        <span class="eb-badge">EuroBasket</span>
        <span class="eb-label">Verified bio + winter career</span>
        <span class="eb-spacer" style="flex:1"></span>
        ${freshness ? `<span class="eb-freshness conf-${confidence}" title="Confidence: ${confidence} · ${sourceCount} source${sourceCount>1?'s':''}">⌁ ${freshness}</span>` : ''}
      </div>
      ${rows.length > 0 ? `<div class="eb-grid">
        ${rows.map(([k, v]) => `
          <div class="eb-row">
            <span class="eb-key">${k}</span>
            <span class="eb-val">${v}</span>
          </div>
        `).join('')}
      </div>` : ''}
      ${recentSeasons.length > 0 ? `
        <div class="eb-history-h">Recent overseas seasons</div>
        <div class="eb-history">
          ${recentSeasons.map(h => `
            <div class="eb-season">
              <span class="eb-year">${h.year}</span>
              <span class="eb-team">${h.team}</span>
              <span class="eb-league">${h.league}</span>
            </div>
          `).join('')}
        </div>
      ` : ''}
    </div>
  `;
}

// Async hook used by app.js — shows skeleton loader, then real data
async function injectEuroBasketDataIntoModal(playerName) {
  const target = document.getElementById('eurobasket-injection');
  if (!target) return;

  // Skeleton loader while fetch runs
  target.innerHTML = `
    <div class="eb-loading">
      <div class="eb-loading-h">Verifying with EuroBasket…</div>
      <div class="skeleton skeleton-line long"></div>
      <div class="skeleton skeleton-line"></div>
      <div class="skeleton skeleton-line short"></div>
    </div>`;

  const cache = await fetchPlayerCache(playerName);
  if (!cache) {
    // No cache — clear skeleton, leave empty
    target.innerHTML = '';
    return;
  }
  target.innerHTML = renderEuroBasketBlock(cache);
}

// Expose globally for use in app.js
window.fetchPlayerCache = fetchPlayerCache;
window.renderEuroBasketBlock = renderEuroBasketBlock;
window.injectEuroBasketDataIntoModal = injectEuroBasketDataIntoModal;
